//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mini_projet1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Ligne_cmd = new HashSet<Ligne_cmd>();
        }
    
        public int id_prod { get; set; }
        public string libelle { get; set; } = string.Empty;
        public float qte { get; set; }
        public byte[] image { get; set; } = null;
        public int id_cat { get; set; }
        public int prix { get; set; } = 0;
        public virtual Categorie Categorie { get; set; } = null;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_cmd> Ligne_cmd { get; set; }
    }
}
